apiVersion: apps/v1beta1

kind: Deployment

metadata:

  name: order-deployment

spec:

  replicas: 1

  template:

    metadata:

      labels:

        app: orders

    spec:

      containers:

      - image: ejmric/orders

        name: orders

        env:

          - name: KUMULUZEE_DISCOVERY_CLUSTER

            value: bluemix

          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS

            value: http://etcd:2379

          - name: KUMULUZEE_CONFIG_ETCD_HOSTS

            value: http://etcd:2379

          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL

            value: jdbc:postgresql://postgres-orders:5432/order

          - name: KUMULUZEE_SERVER_BASEURL

            value: http://169.51.20.118:31715
        

        ports:

        - containerPort: 8081

          name: server

          protocol: TCP
